TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#

LIBRARY_IOC += BioLogicDriver

INC += BioLogicDriver.hpp
#INC += $(ECLAB)/BLFunctions.h
#INC += $(ECLAB)/BLStructs.h

LIB_SRCS += BioLogicDriver.cpp

DBD += BioLogicDriverSupport.dbd


# #=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE